name: Pull Build Test

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: git submodule update --init --recursive
      - run: npm ci
      - run: npm run lint
      - run: npm run vsce-package;
